### PR TITLE
Fix compilation errors after updating cmake_minimum_required (from 3.0) to 3.5

### PR DESCRIPTION
**Pull request by trongnhanuit**
Fix compilation errors caused by updating cmake_minimum_required (from 3.0) to 3.5.

### CODE REVIEW

**Review by bqminh — APPROVED** [review]
all good
